version: '3'
services:

  redis:
    image: redis:5.0-alpine
    ports:
      - "6000:6379"

  forgestatus-server:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      - REDIS_URL=redis:6379
    ports:
      - "5000:80"

  forgestatus-worker-1:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: worker.Dockerfile
    environment:
      - WORKER_ID=1
      - REDIS_URL=redis:6379
    ports:
      - "4001:80"

  forgestatus-worker-2:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: worker.Dockerfile
    environment:
      - WORKER_ID=2
      - REDIS_URL=redis:6379
    ports:
      - "4002:80"
