version: '3'
services:

  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"

  server:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      - REDIS_URL=redis:6379
      - MAX_TASK_QUEUE_SIZE=100
      - MAX_RESULT_QUEUE_SIZE=100
    ports:
      - "5000:80"

  worker-1:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: worker.Dockerfile
    environment:
      - REDIS_URL=redis:6379
      - MAX_TASK_QUEUE_SIZE=100
      - MAX_RESULT_QUEUE_SIZE=100
      - WORKER_ID=1
    ports:
      - "4001:80"

  worker-2:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: worker.Dockerfile
    environment:
      - REDIS_URL=redis:6379
      - MAX_TASK_QUEUE_SIZE=100
      - MAX_RESULT_QUEUE_SIZE=100
      - WORKER_ID=2
    ports:
      - "4002:80"
