version: 2
jobs:
  docker-publish-server:
    machine: true

    working_directory: ~/repo

    steps:
      - checkout

      - run: SERVICE=server ./deploy/push-image.sh

  docker-publish-worker:
    machine: true

    working_directory: ~/repo

    steps:
      - checkout

      - run: SERVICE=worker ./deploy/push-image.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - docker-publish-server
      - docker-publish-worker
