version: 2
jobs:
  create-deploy-config:
    machine: true

    working_directory: ~/repo

    steps:
      - checkout

      - run: ./deploy/create-deploy-config.sh

      - persist_to_workspace:
          root: .
          paths:
            - config

  docker-publish-server:
    machine: true

    working_directory: ~/repo

    steps:
      - checkout

      - run: SERVICE=server ./deploy/build-push-image.sh

  docker-publish-worker:
    machine: true

    working_directory: ~/repo

    steps:
      - checkout

      - run: SERVICE=worker ./deploy/build-push-image.sh

  deploy:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run: ./deploy/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - create-deploy-config
      - docker-publish-server:
          context: forgestatus
      - docker-publish-worker:
          context: forgestatus
      - deploy:
          context: forgestatus
          requires:
            - create-deploy-config
            - docker-publish-server
            - docker-publish-worker
