version: 2
jobs:
  unit-test-server:
    docker:
      - image: golang:1.11-alpine

    working_directory: /go/src/github.com/chrisstowe/forgestatus

    steps:
      - checkout

      - run: go test -v github.com/chrisstowe/forgestatus/forgestatus-server

  unit-test-worker:
    docker:
      - image: golang:1.11-alpine

    working_directory: /go/src/github.com/chrisstowe/forgestatus

    steps:
      - checkout

      - run: go test -v github.com/chrisstowe/forgestatus/forgestatus-worker

  create-deploy-config:
    machine: true

    working_directory: /go/src/github.com/chrisstowe/forgestatus

    steps:
      - checkout

      - run: ./deploy/create-deploy-config.sh

      - persist_to_workspace:
          root: .
          paths:
            - config

  docker-publish-server:
    machine: true

    working_directory: /go/src/github.com/chrisstowe/forgestatus

    steps:
      - checkout

      - run: SERVICE=server ./deploy/build-push-image.sh

  docker-publish-worker:
    machine: true

    working_directory: /go/src/github.com/chrisstowe/forgestatus

    steps:
      - checkout

      - run: SERVICE=worker ./deploy/build-push-image.sh

  deploy:
    docker:
      - image: google/cloud-sdk

    working_directory: /go/src/github.com/chrisstowe/forgestatus

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run: ./deploy/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - unit-test-server
      - unit-test-worker
      - create-deploy-config
      - docker-publish-server:
          context: forgestatus
          requires:
            - unit-test-server
            - unit-test-worker
      - docker-publish-worker:
          context: forgestatus
          requires:
            - unit-test-server
            - unit-test-worker
      - deploy:
          context: forgestatus
          requires:
            - create-deploy-config
            - docker-publish-server
            - docker-publish-worker
