version: 2
jobs:
  unit-test:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/chrisstowe/forgestatus

    steps:
      - checkout

      - run: make unit-test

  integration-test:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/chrisstowe/forgestatus

    steps:
      - checkout

      - run: make integration-test

  create-deploy-config:
    machine: true

    working_directory: ~/repo

    steps:
      - checkout

      - run: ./deploy/create-deploy-config.sh

      - persist_to_workspace:
          root: .
          paths:
            - config

  docker-publish-server:
    machine: true

    working_directory: ~/repo

    steps:
      - checkout

      - run: SERVICE=server ./deploy/build-push-image.sh

  docker-publish-worker:
    machine: true

    working_directory: ~/repo

    steps:
      - checkout

      - run: SERVICE=worker ./deploy/build-push-image.sh

  deploy:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run: ./deploy/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - unit-test
      - integration-test
      - create-deploy-config
      - docker-publish-server:
          context: forgestatus
          requires:
            - unit-test
            - integration-test
      - docker-publish-worker:
          context: forgestatus
          requires:
            - unit-test
            - integration-test
      - deploy:
          context: forgestatus
          requires:
            - create-deploy-config
            - docker-publish-server
            - docker-publish-worker
