apiVersion: v1
kind: Service
metadata:
  name: forgestatus-worker-${WORKER_ID}-service
namespace: ${ENV}
spec:
  type: ClusterIP
  selector:
    app: forgestatus-worker
    workerId: ${WORKER_ID}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
