apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: forgestatus-worker-${WORKER_ID}
  namespace: ${ENV}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: forgestatus-worker
        workerId: "${WORKER_ID}"
    spec:
      containers:
      - name: forgestatus-worker-${WORKER_ID}
        image: gcr.io/forgestatus/forgestatus-worker:${CIRCLE_SHA1}
        imagePullPolicy: Always
        env:
        - name: ENV
          value: "${ENV}"
        - name: PORT
          value: "80"
        - name: REDIS_URL
          value: "forgestatus-redis-service:6379"
        - name: MAX_TASK_QUEUE_SIZE
          value: "100"
        - name: MAX_RESULT_QUEUE_SIZE
          value: "100"
        - name: WORKER_ID
          value: "${WORKER_ID}"
        - name: WORKER_COUNT
          value: "${WORKER_COUNT}"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "0.15Gi"
            cpu: 0.075
          limits:
            memory: "0.3Gi"
            cpu: 0.15
        livenessProbe:
          httpGet:
            path: /status/healthy
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status/ready
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
