apiVersion: v1
kind: Service
metadata:
  name: forgestatus-worker-${WORKER_ID}-service-${ENV}
spec:
  type: ClusterIP
  selector:
    app: forgestatus-worker
    env: ${ENV}
    workerId: ${WORKER_ID}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
