apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: forgestatus-worker-${WORKER_ID}-${ENV}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: forgestatus-worker-${WORKER_ID}-${ENV}
    spec:
      containers:
      - name: forgestatus-worker-${WORKER_ID}-${ENV}
        image: gcr.io/forgestatus/forgestatus-worker:${CIRCLE_SHA1}
        imagePullPolicy: Always
        env:
        - name: REDIS_URL
          value: "http://forgestatus-redis-service-${ENV}:6379"
        - name: WORKER_ID
          value: "${WORKER_ID}"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
